### ISSUE TITLE
Problema: Template Postfix Services: Postfix queue 

### ISSUE THREAD

**Issue by walterbrazolin** [rafael747/zabbix-postfix#1]
Template Postfix Services:

Chave:
![zabbix](https://user-images.githubusercontent.com/42981930/55083066-9a39e700-5081-11e9-8acf-b7a7109048b0.jpg)

 Postfix queue consta como "Não suportado" "

Unsupported item key."

Todas as configurações, automáticas por scritpt e manual foram realizadas.

Zabbix 4.0.0. - centos 7.

**Comment by rafael747** [comment]
Por favor, verifique se o seguinte comando retorna o tamanho da fila de email:

`sudo /usr/bin/mailq | grep -v "Mail queue is empty" | grep -c '^[0-9A-Z]'`

Lembrando que o vai ser o zabbix-agent que vai executar esse comando, então deve estar na configuração do sudoers: "zabbix ALL=NOPASSWD:/usr/bin/mailq"

**Comment by walterbrazolin** [comment]
Responde:

Abraços
Atenciosamente,

Walter Brazolin 

    Em quarta-feira, 27 de março de 2019 11:55:28 BRT, Rafael Carreira <notifications@github.com> escreveu:  
 
 
Por favor, verifique se o seguinte comando retorna o tamanho da fila de email:

sudo /usr/bin/mailq | grep -v "Mail queue is empty" | grep -c '^[0-9A-Z]'

Lembrando que o vai ser o zabbix-agent que vai executar esse comando, então deve estar na configuração do sudoers: "zabbix ALL=NOPASSWD:/usr/bin/mailq"

**Comment by walterbrazolin** [comment]
Os dois comandos estão ok.

![zabbix2](https://user-images.githubusercontent.com/42981930/55088115-eee16000-5089-11e9-9af1-78d824853b63.jpg)
![zabbix3](https://user-images.githubusercontent.com/42981930/55088116-eee16000-5089-11e9-8df1-d71cc1645372.jpg)

**Comment by rafael747** [comment]
Por favor, verifique os seguintes itens:

que o arquivo "zabbix_postfix.conf" está em "/etc/zabbix/zabbix_agentd.conf.d/"
que existe a linha "Include=/etc/zabbix/zabbix_agentd.conf.d/*.conf" em "/etc/zabbix/zabbix_agentd.conf"

e que os serviços "sudo" e "zabbix-agent" fora reiniciados

service sudo restart
service zabbix-agent restart


Adicionalmente, verifique se ocorre algum erro no arquivo de log: "/var/log/zabbix-agent/zabbix_agentd.log"

**Comment by rafael747** [comment]
Você também pode realizar a requisição para esse item manualmente, a partir do zabbix server:

zabbix_get -k pf.mailq -s <ip_servidor>

**Comment by walterbrazolin** [comment]
Acho que era problema no agent. Retirei tudo e qualquer fragmento dele e começando do zero funcionou. Estão em Rio Preto e acho que você também. Obrigado pela ajuda. Agora vou criar as triggers.

**Comment by rafael747** [comment]
Sou de Rio Preto sim. Eu já mexi bastante com Zabbix, com itens customizados, templates, etc..
Se você precisar de ajuda com qualquer coisa é só chamar.
