### ISSUE TITLE
Postfix queue is unsupported item key

### ISSUE THREAD

**Issue by pthoelken** [rafael747/zabbix-postfix#11]
Hey Rafael, 

Thanks for these postfix monitoring. 

I've imported to my server and I've got the error from "Postfix queue" that there is a unsupported item key. 

![image](https://user-images.githubusercontent.com/12643853/175791882-60ab52de-294e-4067-b658-f52881676072.png)

Also I have to change the line 1 for interpreter in this script to `python3` https://github.com/rafael747/zabbix-postfix/blob/master/pygtail.py#L1 to work with my environment. 

All other things in this script works well. 

Do you know why I got the "unsupported item key"?

**Comment by rafael747** [comment]
Hello @pthoelken

Did you restated the zabbix agent after coping this file: https://github.com/rafael747/zabbix-postfix/blob/master/zabbix_postfix.conf

Also, notice that the location of this file may change depending on the system
If this is not the issue, can you manually run the command? 
> sudo /usr/bin/mailq | grep -v "Mail queue is empty" | grep -c '^[0-9A-Z]'

**Comment by pthoelken** [comment]
Yes, I've restarted the agent. Here the information for you, which I have: 

```
root@server:~# /usr/local/sbin/zabbix_postfix.sh
Response from "monitor.foo.bar:10051": "processed: 1; failed: 0; total: 1; seconds spent: 0.000156"
sent: 1; skipped: 0; total: 1
Response from "monitor.foo.bar:10051": "processed: 1; failed: 0; total: 1; seconds spent: 0.000162"
sent: 1; skipped: 0; total: 1
Response from "monitor.foo.bar:10051": "processed: 1; failed: 0; total: 1; seconds spent: 0.000155"
sent: 1; skipped: 0; total: 1
Response from "monitor.foo.bar:10051": "processed: 1; failed: 0; total: 1; seconds spent: 0.000155"
sent: 1; skipped: 0; total: 1
Response from "monitor.foo.bar:10051": "processed: 1; failed: 0; total: 1; seconds spent: 0.000165"
sent: 1; skipped: 0; total: 1
Response from "monitor.foo.bar:10051": "processed: 1; failed: 0; total: 1; seconds spent: 0.000251"
sent: 1; skipped: 0; total: 1
Response from "monitor.foo.bar:10051": "processed: 1; failed: 0; total: 1; seconds spent: 0.000154"
sent: 1; skipped: 0; total: 1
Response from "monitor.foo.bar:10051": "processed: 1; failed: 0; total: 1; seconds spent: 0.000171"
sent: 1; skipped: 0; total: 1
Response from "monitor.foo.bar:10051": "processed: 1; failed: 0; total: 1; seconds spent: 0.000152"
sent: 1; skipped: 0; total: 1
Response from "monitor.foo.bar:10051": "processed: 1; failed: 0; total: 1; seconds spent: 0.000162"
sent: 1; skipped: 0; total: 1
Response from "monitor.foo.bar:10051": "processed: 1; failed: 0; total: 1; seconds spent: 0.000160"
sent: 1; skipped: 0; total: 1
root@server:~# /usr/bin/mailq | grep -v "Mail queue is empty" | grep -c '^[0-9A-Z]'
0
root@server:~# 
```

But still the message "unsupported item key"

**Comment by rafael747** [comment]
You can also check:
 - if the sudo service was restated (service sudo restart)
 - If zabbix agent is actually reading that config file
 - if the host is accessible to zabbix server
 - if you can manually retrieve the item (zabbix_get -k pf.mailq -s HOST)
 - zabbix agent logs ("/var/log/zabbix-agent/zabbix_agentd.log")

**Comment by pthoelken** [comment]
- sudo can't restart because it's masked service.
- Of course the agent can read the config file all other monitoring, and all other items from your script are working
- yep 
- zabbix_get is not available on the client-host

Log looks all good as well 
```
655888:20220627:091859.479 using configuration file: /etc/zabbix/zabbix_agentd.conf
655888:20220627:091859.479 agent #0 started [main process]
655889:20220627:091859.479 agent #1 started [collector]
655890:20220627:091859.480 agent #2 started [listener #1]
655891:20220627:091859.480 agent #3 started [listener #2]
655892:20220627:091859.480 agent #4 started [listener #3]
655893:20220627:091859.481 agent #5 started [active checks #1] 
```

All other things in your script are working: 

![image](https://user-images.githubusercontent.com/12643853/175882314-c38cb89e-4367-4eef-ab19-90023e05780e.png)

**Comment by rafael747** [comment]
Can you try the `zabbix_get` command in the zabbix server?

all the other items are active items (the host send the metric to zabbix server), so they work a bit differently

**Comment by pthoelken** [comment]
`zabbix_get` is not available on the zabbix server. 

```
root@xxx-srv-monitor01:~# zabbix_get
-bash: zabbix_get: command not found
```

```
root@xxx-srv-monitor01:~# which zabbix_get
root@xxx-srv-monitor01:~# 
```

**Comment by rafael747** [comment]
can you install it?
`# yum install zabbix-get`
`# apt install zabbix-get`

**Comment by pthoelken** [comment]
Now I get these output: 

```
root@xxx-srv-monitor01:~# zabbix_get -k pf.mailq -s myhost.foo.bar
zabbix_get [3062]: Check access restrictions in Zabbix agent configuration
```

**Comment by rafael747** [comment]
can you check if `Server` and `ServerActive` are correct (with server's IP) in zabbix agent config
also check the zabbix agent logs when you use `zabbix-get`

**Comment by pthoelken** [comment]
These are the values on the postfix-host
```
Server=monitor.foobar.com
ServerActive=monitor.foobar.com
```

Seems to be correct. 

Was problem from psk .. fix this with these lines .. and check the output. 

```
root@xxx-srv-monitor01:~# zabbix_get --tls-connect psk --tls-psk-identity psk-xxx-id --tls-psk-file auth.psk -k pf.mailq -s myhost.foo.bar
ZBX_NOTSUPPORTED: Unsupported item key.
```

with the new zabbix_get, there a no new entrie in the log from postfix-host.

**Comment by rafael747** [comment]
I'm actually out of ideas

maybe you can change `DebugLevel` in the agent and test again

**Comment by pthoelken** [comment]
Fixed now. Maybe it's needs some time.
