### ISSUE TITLE
Template will not import into Zabbix 7.0.0alpha1

### ISSUE THREAD

**Issue by elyograg** [rafael747/zabbix-postfix#17]
I opted to set up the new Zabbix alpha version from scratch.

This template will not import into 7.0.0alpha1.  "Unexpected Server Error" is shown.  There is nothing useful in the apache logs.  I am importing the standard template, not the passive template.

**Comment by elyograg** [comment]
Before I rebuilt my server with 7.0 from scratch, I did upgrade the previous version to 7.0.0alpha1.  I still had a copy of that database dump, so I set up a second server with that database, and exported the upgraded template.  Then I was able to import that into my new 7.0.0alpha1 server.  Here is that exported template:

[postfix_services_template_7.0.zip](https://github.com/rafael747/zabbix-postfix/files/11702148/postfix_services_template_7.0.zip)

**Comment by rafael747** [comment]
Hello @elyograg 

I just tested with Zabbix 7.0.0alpha2 (curently in master with no tags) and I had no issues to import both templates
Nevertheless, thank you for raising the issue with 7.0.0alpha1 and providing a copy of the template that works with this version
I will include both templates in this comment in case someone wants to import specifically in 7.0.0alpha1

[templates_postfix_7.0.zip](https://github.com/rafael747/zabbix-postfix/files/11747719/templates_postfix_7.0.zip)
