### ISSUE TITLE
Instruction updates for zabbix-agent2, and for the crontab entry

### ISSUE THREAD

**Issue by elyograg** [rafael747/zabbix-postfix#7]
At first I thought the reason the cron entry wasn't working was because I had put it in the zabbix user's crontab instead of root.  But even after switching that, it didn't work.  Eventually I figured out that it was because it was looking for /etc/zabbix/zabbix_agentd.conf instead of /etc/zabbix/zabbix_agent2.conf.

**Comment by rafael747** [comment]
Hello @elyograg 

Can you tell me if changing this [line](https://github.com/rafael747/zabbix-postfix/blob/master/zabbix_postfix.sh#L15) to:

`ZABBIX_CONF=/etc/zabbix/zabbix_agent2.conf`

solves the issue?

**Comment by elyograg** [comment]
Yes, that change fixed the sending script.

The instructions in the README would not have worked if I had followed them precisely ... some changes were required for agent2.

**Comment by rafael747** [comment]
Thank you for the reply,
I will update the README to also include agent2 specifics.
can you tell me if there was other changes necessary to make it work with agent2?

**Comment by rafael747** [comment]
Instructions for zabbix-agent2 added to README.md and zabbix_postfix.sh
