### ISSUE TITLE
last apostrophe unnecessary

### ISSUE THREAD

**Issue by pawlab1** [rafael747/zabbix-postfix#8]
Add crontab entry

# Zabbix check
*/5 * * * * /usr/local/sbin/zabbix_postfix.sh 1>/dev/null 2>/dev/null'

correct
*/5 * * * * /usr/local/sbin/zabbix_postfix.sh 1>/dev/null 2>/dev/null

**Comment by rafael747** [comment]
Hello,
Just fixed, thanks
